"""Delivery Monitor and Escalation Engine — Phase 5's HTTP surface (CLAUDE.md §8).

    GET /monitoring/alerts   the internal alert feed, with SLA escalations
    GET /monitoring/rules    the shipped SLA rule table, as policy

`app/services/monitoring/` and `app/services/escalation/` were fully built and
tested with nothing able to call them. This module is the call: it reads the
systems of record, shapes them into a `MonitorContext` / `SlaFacts`, and
serialises what the two pure services hand back. No detector, no threshold, no
weight and no comparison is reimplemented here — grep this file for a number and
the only ones you will find are a period-length guard and an hours-per-hour
divisor.

CEILING: ALERT, INTERNAL ONLY (§8)
==================================
"Delivery Monitor — attendance, usage, syllabus anomalies, risk scoring.
Ceiling: **Alert (internal only)**." That is autonomy level 1, Observe: read,
report, alert internally.

Both endpoints are `GET`. Nothing here sends, notifies, queues an outbound comm,
marks, acknowledges, resolves, approves or releases anything (R3, R4), and
nothing here writes a row of any kind — not even an audit row, because §11 wants
audit rows for state *transitions* and a read is not one. `escalation.raised` /
`escalation.routed` (`app/services/escalation/audit.py`) belong to the scheduled
evaluation that persists escalations; that path does not exist yet and this
module deliberately does not become it by writing from a GET handler.

`build_alert()` refuses an external audience, and the audience passed below is
always `(principal.persona,)` behind `require_internal()`. A trainer or a College
login is refused before a single row is read.

NO LLM (§8)
===========
"Escalation Engine — deterministic SLA rules. **Not LLM judgement.**" This module
imports nothing from `app.core.llm` or `app.agents`, and neither endpoint takes
an `include_narrative`-style flag. Every escalation below is a `Decimal` compared
to a `Decimal` threshold from `DEFAULT_RULES`, and its `reason` is generated by
`SlaRule.explain()` from the rule row itself.

R5 / §4 — WHERE THE WALL IS
===========================
We are on a `BYPASSRLS` service-role connection (`app/db/session.py`), so the
policies never run for us and reach is enforced in code, exactly as `reports.py`
and `programs.py` do it. `_reachable_programs()` is the wall: the SQL predicate
narrows the read, and the Python filter after it is what actually guarantees the
result, because on this connection the database will happily hand back every
college in the country. An LDE Executive therefore sees their own campus and
zero rows for anything else — `tests/unit/test_api_monitoring.py` asserts the
zero, not the 403.

COMMERCIALS: NOTHING HERE IS BEHIND THAT WALL, AND THAT IS CHECKED, NOT ASSUMED
==============================================================================
§4 gives an LDE Executive "attendance, batches, daily tasks. **No commercials**",
and this feed is squarely their daily work — so the question is whether any
figure that leaves this module is commercial. Audited field by field:

* Anomaly `detail` (`app/services/monitoring/detectors.py`) carries day counts,
  dates, hour counts, absence rates, active-learner counts and syllabus
  percentages. No amount, no rate, no invoice.
* Escalation `measured` / `threshold` are hours, unmarked-day counts and the
  monitor's own risk score. `SlaMetric` has no monetary member.
* Trainer identity is surfaced as `full_name` only. PAN seeds the invoice number
  (§6) and is deliberately not exported here.

So `require_commercials()` is **not** called, and the omission is the finding
rather than an oversight. Two consequences follow and are honoured below:

* `SlaMetric.PAYOUT_HOURS_BLOCKED` is left UNMEASURED. Measuring it means reading
  `remuneration_sheets`, which is behind the wall, and half-populating this feed
  for a Manager and not an LDE Executive would put a commercial-visibility branch
  inside a non-commercial screen. When a payout-blocked escalation is wanted it
  belongs in `payouts.py`, behind `require_commercials()`.
* If a monetary field is ever added to an anomaly, an SLA metric or this
  response, this endpoint must gain `require_commercials()` in the same diff.

WHAT IS DELIBERATELY DARK
=========================
Five of the nine detectors cannot fire from this endpoint today, and none of them
is faked. `DETECTORS` is 4 attendance + 2 usage + 3 syllabus; attendance is the
only family with a table behind it, so the two usage and three syllabus detectors
are dark. (This paragraph read "four" while already listing five function names
below — the prose was wrong, not the list.)

* usage (`detect_no_activity`, `detect_low_active_share`) — §14 Q6 is open
  ("EdTech platform access: direct DB, API, or neither?"), so there is no
  platform-engagement row anywhere in `app/db/models.py`. `attendance_records` is
  STUDENT class attendance and mapping it onto `UsageSignal` would report a
  delivery fact the platform never said (R1).
* syllabus (`detect_syllabus_*`) — no column stores a completion reading.

`MonitorContext.usage` and `.syllabus` are therefore `None`, which the detectors
already treat as "silent", and `SlaMetric.ESCALATION_HOURS_UNACKNOWLEDGED` is
unmeasured because no `escalations` table exists to have gone unacknowledged.
"Not measured is not zero" is the engine's own rule; this module obeys it by
omitting the key rather than passing a placeholder.
"""

from __future__ import annotations

import calendar
import datetime as dt
from collections import defaultdict
from collections.abc import Iterable, Sequence
from decimal import Decimal
from typing import Annotated, Any, Final
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, ConfigDict, PlainSerializer
from sqlalchemy import ColumnExpressionArgument, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import InstrumentedAttribute

from app.core.security import (
    CurrentPrincipal,
    Principal,
    require_college_reach,
    require_internal,
)
from app.db.models import (
    Batch,
    College,
    Deployment,
    Profile,
    Program,
    ProgramDocument,
    Task,
    Trainer,
    TrainerAttendance,
    UserClusterAssignment,
    UserCollegeAssignment,
)
from app.db.session import get_session
from app.domain.attendance import expand_period
from app.domain.enums import AttendanceMark, DocStatus, Persona, ProgramType, TaskStatus
from app.domain.risk import (
    TIER_PERSONA,
    EscalationTier,
    RiskBand,
    SlaMetric,
    band_for_score,
)
from app.services.escalation import (
    DEFAULT_RULES,
    EscalationRecipients,
    SlaFacts,
    SlaRule,
    evaluate_sla,
    resolve_recipients,
)
from app.services.monitoring import (
    Anomaly,
    AttendanceSignal,
    MonitorContext,
    RiskAssessment,
    assess_risk,
    build_alert,
)

router = APIRouter(prefix="/monitoring", tags=["monitoring"])

Session = Annotated[AsyncSession, Depends(get_session)]

#: Longest observation window a single request may open. A period is materialised
#: day by day per deployment (`expand_period`, which is the only way "unmarked"
#: is visible at all), so an unbounded range is an unbounded expansion. Three
#: months covers a quarter-end review and refuses a "since 2019" typo.
MAX_PERIOD_DAYS: Final[int] = 92

#: Scores and thresholds leave as strings. Same reasoning as
#: `app.api.reports.MoneyOut`: Pydantic would otherwise serialise a `Decimal` as
#: a JSON float, and a risk score that renders differently to the score the
#: engine banded is a number nobody can reconcile.
DecimalOut = Annotated[Decimal, PlainSerializer(str, return_type=str, when_used="json")]

#: Persona to escalation tier — the inverse of `app.domain.risk.TIER_PERSONA`,
#: derived rather than retyped so the two cannot drift apart.
_TIER_BY_PERSONA: Final[dict[Persona, EscalationTier]] = {
    persona: tier for tier, persona in TIER_PERSONA.items()
}

#: `(tier, college_id) -> user ids`, the pre-resolved form of `ReachDirectory`.
_TierMap = dict[tuple[EscalationTier, UUID], tuple[UUID, ...]]

_SECONDS_PER_HOUR: Final[Decimal] = Decimal(3600)
_HOURS = Decimal("0.01")


# --- responses ----------------------------------------------------------------


class AnomalyOut(BaseModel):
    """One thing the Delivery Monitor observed. Never a conclusion (§8)."""

    model_config = ConfigDict(frozen=True)

    code: str
    severity: str
    message: str
    detail: dict[str, str]

    @classmethod
    def of(cls, anomaly: Anomaly) -> AnomalyOut:
        return cls(
            code=anomaly.code.value,
            severity=anomaly.severity.value,
            message=anomaly.message,
            # Already `str`-valued at construction (`detectors._anomaly`), so this
            # copies the operative figures out without reformatting one of them.
            detail=dict(anomaly.detail),
        )


class DeploymentRiskOut(BaseModel):
    """One trainer-on-a-batch, assessed. The grain `trainer_attendance` is kept at.

    The monitor is not run per program: a program with three deployments has three
    tracksheets, and `expand_period()` requires each calendar day exactly once, so
    merging them would duplicate days and make "unmarked" incalculable. The
    program-level score above is the worst of these, never their sum.
    """

    model_config = ConfigDict(frozen=True)

    deployment_id: UUID
    trainer_name: str
    batch_name: str
    period_start: dt.date
    period_end: dt.date
    elapsed_through: dt.date
    score: DecimalOut
    band: RiskBand
    #: `InternalAlert.headline` and `.lines`, exactly as `alerts.build_alert()`
    #: rendered them for this caller's persona. Rendered text, never a fact — the
    #: structured `anomalies` below are what a client should compute from (R1).
    headline: str
    lines: tuple[str, ...]
    anomalies: tuple[AnomalyOut, ...]


class EscalationOut(BaseModel):
    """One SLA rule that fired, with the numbers that made it fire, and where it landed.

    `reason` is `SlaRule.explain()` plus the measured value — generated from the
    rule row, not written about it, so an escalation whose explanation disagrees
    with its threshold is not expressible.
    """

    model_config = ConfigDict(frozen=True)

    code: str
    metric: str
    comparison: str
    measured: DecimalOut
    threshold: DecimalOut
    severity: str
    reason: str
    requested_tier: EscalationTier
    resolved_tier: EscalationTier
    recipient_persona: Persona
    #: How many internal users at `resolved_tier` reach this college. Ids are not
    #: exported: the count and the tier are what `escalation.routed` records, and
    #: a feed that names individuals invites being read as an assignment.
    recipient_count: int
    #: True when an unstaffed rung was climbed (§4). A Senior Manager asking "why
    #: is this on my desk" reads it here.
    climbed: bool
    #: True when no internal user could be found on any rung. An ops gap in the
    #: assignment tables, surfaced rather than raised.
    unrouted: bool

    @classmethod
    def of(cls, routed: EscalationRecipients) -> EscalationOut:
        e = routed.escalation
        return cls(
            code=e.code.value,
            metric=e.metric.value,
            comparison=e.comparison.value,
            measured=e.measured,
            threshold=e.threshold,
            severity=e.severity.value,
            reason=e.reason,
            requested_tier=routed.requested_tier,
            resolved_tier=routed.resolved_tier,
            recipient_persona=routed.persona,
            recipient_count=len(routed.user_ids),
            climbed=routed.requested_tier is not routed.resolved_tier,
            unrouted=routed.is_unrouted,
        )


class ProgramRiskOut(BaseModel):
    """One program's delivery risk, its deployments and its SLA escalations."""

    model_config = ConfigDict(frozen=True)

    program_id: UUID
    program_name: str
    program_type: ProgramType
    college_id: UUID
    college_name: str
    stage: str
    #: The worst deployment's score, not the sum. Summing would make a program
    #: with six healthy trainers read as riskier than one with a single stalled
    #: tracksheet, which inverts the thing the feed is sorted by.
    score: DecimalOut
    band: RiskBand
    deployments: tuple[DeploymentRiskOut, ...]
    escalations: tuple[EscalationOut, ...]
    #: Metrics the rule table can refer to but which nothing measured for this
    #: program. Listed because "not measured is not zero" (`engine.py`) is
    #: invisible otherwise — a silent rule and a passing rule look identical.
    unmeasured_metrics: tuple[str, ...]


class AlertFeedOut(BaseModel):
    """The whole internal feed for one observation window."""

    model_config = ConfigDict(frozen=True)

    as_of: dt.datetime
    period_start: dt.date
    period_end: dt.date
    #: Persona the alert text was rendered for. Always the caller's, always
    #: internal — `build_alert()` refuses anything else (§8).
    audience: Persona
    programs: tuple[ProgramRiskOut, ...]
    program_count: int
    deployment_count: int
    escalation_count: int
    #: Programs per band, highest first. The dashboard's only aggregate.
    band_counts: dict[str, int]


class SlaRuleOut(BaseModel):
    """One row of the shipped SLA rule table, rendered as the policy it is."""

    model_config = ConfigDict(frozen=True)

    code: str
    metric: str
    comparison: str
    threshold: DecimalOut
    #: `None` in the table means "one rung above whoever owns this now" (§4),
    #: which is a resolution rule and not an absolute tier — so it is `None` here
    #: too rather than being flattened into a tier it is not.
    tier: EscalationTier | None
    severity: str
    program_type: ProgramType | None
    rationale: str
    explanation: str
    #: False when nothing in this deployment measures the rule's metric, so the
    #: rule cannot currently fire. See the module docstring.
    is_measured: bool

    @classmethod
    def of(cls, rule: SlaRule, *, measured: bool) -> SlaRuleOut:
        return cls(
            code=rule.code.value,
            metric=rule.metric.value,
            comparison=rule.comparison.value,
            threshold=rule.threshold,
            tier=rule.tier,
            severity=rule.severity.value,
            program_type=rule.program_type,
            rationale=rule.rationale,
            explanation=rule.explain(),
            is_measured=measured,
        )


class SlaRulesOut(BaseModel):
    """`DEFAULT_RULES`, in table order. The escalation policy, readable."""

    model_config = ConfigDict(frozen=True)

    rules: tuple[SlaRuleOut, ...]
    measured_metrics: tuple[str, ...]
    unmeasured_metrics: tuple[str, ...]


# --- endpoints ----------------------------------------------------------------


@router.get(
    "/alerts",
    response_model=AlertFeedOut,
    status_code=status.HTTP_200_OK,
    summary="Internal delivery-risk alerts and SLA escalations across the caller's reach",
)
async def alert_feed(
    principal: CurrentPrincipal,
    session: Session,
    program_id: Annotated[UUID | None, Query()] = None,
    college_id: Annotated[UUID | None, Query()] = None,
    period_start: Annotated[dt.date | None, Query()] = None,
    period_end: Annotated[dt.date | None, Query()] = None,
    as_of: Annotated[dt.datetime | None, Query()] = None,
) -> AlertFeedOut:
    """Run the Delivery Monitor and the Escalation Engine over everything in reach.

    Internal only, and available to an LDE Executive: attendance and batches are
    §4's description of their day, and nothing in this response is commercial —
    see the module docstring, which audits that field by field.

    Computed on request rather than read from a table. There is no `alerts` or
    `escalations` table in `supabase/migrations/`, and inventing one from a read
    endpoint is not this workstream's to do; both services are pure functions of
    signals that are already stored, so the feed is reproducible from its inputs.
    Pass `as_of` to reproduce a past run exactly — nothing below reads a clock
    once that argument is bound.

    `period_start` / `period_end` default to the calendar month containing
    `as_of`, which is the period a payout cycle is cut on (§6).
    """
    require_internal(principal)
    observed_at = _as_of(as_of)
    start, end = _period(period_start, period_end, observed_at)

    programs = await _reachable_programs(session, principal, program_id, college_id)
    colleges = {
        c.id: c
        for c in await _all(
            session, College, College.id.in_([p.college_id for p in programs]) if programs else None
        )
    }

    batches = await _in(session, Batch, Batch.program_id, [p.id for p in programs])
    batches_by_program: dict[UUID, list[Batch]] = defaultdict(list)
    for batch in batches:
        batches_by_program[batch.program_id].append(batch)

    deployments = await _in(session, Deployment, Deployment.batch_id, [b.id for b in batches])
    trainers = {
        t.id: t
        for t in await _in(session, Trainer, Trainer.id, [d.trainer_id for d in deployments])
    }
    batch_names = {b.id: b.name for b in batches}

    marks = await _marks(session, [d.id for d in deployments], start, end)
    tasks = await _in(session, Task, Task.program_id, [p.id for p in programs])
    documents = await _in(
        session, ProgramDocument, ProgramDocument.program_id, [p.id for p in programs]
    )
    directory = await _staff_directory(session, [p.college_id for p in programs])

    deployments_by_batch: dict[UUID, list[Deployment]] = defaultdict(list)
    for deployment in deployments:
        deployments_by_batch[deployment.batch_id].append(deployment)

    out: list[ProgramRiskOut] = []
    for program in programs:
        program_deployments = [
            d for b in batches_by_program[program.id] for d in deployments_by_batch[b.id]
        ]
        assessed = _assess_deployments(program, program_deployments, marks, start, end, observed_at)
        rendered = tuple(
            _deployment_out(
                deployment,
                assessment,
                signal,
                principal.persona,
                trainer_name=(
                    trainers[deployment.trainer_id].full_name or "unnamed"
                    if deployment.trainer_id in trainers
                    else "unknown"
                ),
                batch_name=batch_names.get(deployment.batch_id, "unknown"),
            )
            for deployment, assessment, signal in assessed
        )

        metrics = _sla_metrics(
            assessed,
            [t for t in tasks if t.program_id == program.id],
            [d for d in documents if d.program_id == program.id],
            observed_at,
        )
        decision = evaluate_sla(
            SlaFacts(
                subject_table="programs",
                subject_id=program.id,
                program_id=program.id,
                college_id=program.college_id,
                program_type=program.type,
                as_of=observed_at,
                metrics=metrics,
            )
        )
        escalations: list[EscalationOut] = []
        for fired in decision.escalations:
            # Routing climbs unstaffed rungs (§4), so it is resolved per firing
            # rather than once per program: two rules on one program can start at
            # different tiers and land in different places.
            escalations.append(EscalationOut.of(await resolve_recipients(fired, directory)))

        score = max((a.score for _, a, _ in assessed), default=Decimal(0))
        college = colleges.get(program.college_id)
        out.append(
            ProgramRiskOut(
                program_id=program.id,
                program_name=program.name,
                program_type=program.type,
                college_id=program.college_id,
                college_name=college.name if college else "unknown",
                stage=program.stage.value,
                score=score,
                band=band_for_score(score),
                deployments=rendered,
                escalations=tuple(escalations),
                unmeasured_metrics=_unmeasured(metrics),
            )
        )

    out.sort(key=lambda p: (-p.score, p.college_name, p.program_name))
    band_counts = {band.value: sum(1 for p in out if p.band is band) for band in RiskBand}
    return AlertFeedOut(
        as_of=observed_at,
        period_start=start,
        period_end=end,
        audience=principal.persona,
        programs=tuple(out),
        program_count=len(out),
        deployment_count=sum(len(p.deployments) for p in out),
        escalation_count=sum(len(p.escalations) for p in out),
        band_counts=band_counts,
    )


@router.get(
    "/rules",
    response_model=SlaRulesOut,
    status_code=status.HTTP_200_OK,
    summary="The shipped SLA rule table — the escalation policy, as data",
)
async def sla_rules(principal: CurrentPrincipal) -> SlaRulesOut:
    """`DEFAULT_RULES` verbatim, in table order.

    §8's promise is that "a reviewer can read why something escalated without
    running anything", and that only holds if the rule table is readable by the
    people the escalations land on. Internal only for the same reason the feed is:
    the rungs it names are the §4 chain, which is byteXL's org chart.

    Nothing here is configurable through this endpoint, and there is no PUT. A
    rule change is an edit to `rules.py` in a diff someone reviews — a threshold
    editable at runtime is a threshold nobody can reconstruct after the fact.
    """
    require_internal(principal)
    return SlaRulesOut(
        rules=tuple(
            SlaRuleOut.of(rule, measured=rule.metric in MEASURED_METRICS) for rule in DEFAULT_RULES
        ),
        measured_metrics=tuple(sorted(m.value for m in MEASURED_METRICS)),
        unmeasured_metrics=tuple(sorted(m.value for m in SlaMetric if m not in MEASURED_METRICS)),
    )


# --- authorisation ------------------------------------------------------------


async def _reachable_programs(
    session: AsyncSession,
    principal: Principal,
    program_id: UUID | None,
    college_id: UUID | None,
) -> list[Program]:
    """Every program the caller reaches, optionally narrowed to one.

    THE WALL (R5). On a `BYPASSRLS` connection the SQL predicate is an
    optimisation and the Python filter is the guarantee — the database will
    return every program in the estate if asked, so the last line here is what
    makes an LDE Executive's feed contain their campus and nothing else.

    A named `program_id` or `college_id` outside reach is a 403 rather than an
    empty list: the caller asserted something specific and is entitled to be told
    it was refused. An unnamed sweep is silently narrowed, because "everything you
    reach" cannot be refused.
    """
    if program_id is not None:
        program = await session.get(Program, program_id)
        if program is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Program not found")
        require_college_reach(principal, program.college_id)
        if college_id is not None and program.college_id != college_id:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="That program does not belong to that college",
            )
        return [program]

    if college_id is not None:
        require_college_reach(principal, college_id)
        scope = frozenset({college_id})
    else:
        scope = principal.college_ids

    if not scope:
        return []
    rows = await _all(session, Program, Program.college_id.in_(scope))
    return [p for p in rows if p.college_id in scope]


# --- reading ------------------------------------------------------------------


async def _all(
    session: AsyncSession, model: type[Any], *criteria: ColumnExpressionArgument[bool] | None
) -> Sequence[Any]:
    """`SELECT * FROM model WHERE ...`, as a list. The only query shape here."""
    where = [c for c in criteria if c is not None]
    return (await session.execute(select(model).where(*where))).scalars().all()


async def _in(
    session: AsyncSession,
    model: type[Any],
    column: InstrumentedAttribute[Any],
    values: Iterable[UUID],
) -> list[Any]:
    """`WHERE column IN (...)`, short-circuiting on an empty list.

    An empty `IN ()` is legal SQL that matches nothing, but building the statement
    at all costs a round trip per empty level, and the levels nest four deep here.
    """
    unique = sorted(set(values))
    if not unique:
        return []
    return list(await _all(session, model, column.in_(unique)))


async def _marks(
    session: AsyncSession, deployment_ids: Sequence[UUID], start: dt.date, end: dt.date
) -> dict[UUID, list[TrainerAttendance]]:
    """Every trainer-day mark in the window, grouped by deployment."""
    rows = (
        await _all(
            session,
            TrainerAttendance,
            TrainerAttendance.deployment_id.in_(sorted(set(deployment_ids))),
            TrainerAttendance.mark_date >= start,
            TrainerAttendance.mark_date <= end,
        )
        if deployment_ids
        else []
    )
    grouped: dict[UUID, list[TrainerAttendance]] = defaultdict(list)
    for row in rows:
        grouped[row.deployment_id].append(row)
    return grouped


class _StaffDirectory:
    """`ReachDirectory` (`app/services/escalation/targets.py`) bound to the database.

    Pre-resolved into a mapping rather than querying per escalation: a feed over
    thirty programs raises the same tiers against the same colleges over and over,
    and the Protocol requires a stable order across calls, which one sorted build
    gives for free.

    Reach is read from `user_college_assignments` and `user_cluster_assignments`
    with `colleges.cluster_id` expanding a cluster (§4) — never inferred from
    `profiles.college_id`, which serves the College persona alone.
    """

    __slots__ = ("_by_tier_college",)

    def __init__(self, by_tier_college: _TierMap) -> None:
        self._by_tier_college = by_tier_college

    async def users_at_tier(self, tier: EscalationTier, college_id: UUID) -> tuple[UUID, ...]:
        return self._by_tier_college.get((tier, college_id), ())


async def _staff_directory(session: AsyncSession, college_ids: Sequence[UUID]) -> _StaffDirectory:
    """Who, on each rung, reaches each college in scope."""
    scope = sorted(set(college_ids))
    if not scope:
        return _StaffDirectory({})

    profiles = await _all(session, Profile, Profile.role.in_(sorted(_TIER_BY_PERSONA)))
    tier_of = {p.id: _TIER_BY_PERSONA[p.role] for p in profiles if p.role in _TIER_BY_PERSONA}

    reach: dict[UUID, set[UUID]] = defaultdict(set)
    for row in await _in(session, UserCollegeAssignment, UserCollegeAssignment.college_id, scope):
        reach[row.college_id].add(row.user_id)

    colleges = await _in(session, College, College.id, scope)
    by_cluster: dict[UUID, list[UUID]] = defaultdict(list)
    for college in colleges:
        if college.cluster_id is not None:
            by_cluster[college.cluster_id].append(college.id)
    if by_cluster:
        cluster_rows = await _in(
            session, UserClusterAssignment, UserClusterAssignment.cluster_id, list(by_cluster)
        )
        for row in cluster_rows:
            for cid in by_cluster.get(row.cluster_id, ()):
                reach[cid].add(row.user_id)

    grouped: _TierMap = {}
    for cid, user_ids in reach.items():
        per_tier: dict[EscalationTier, list[UUID]] = defaultdict(list)
        for user_id in user_ids:
            tier = tier_of.get(user_id)
            if tier is not None:
                per_tier[tier].append(user_id)
        for tier, ids in per_tier.items():
            # Stable order is part of the Protocol: an escalation that names its
            # recipients differently on every run is not deterministic.
            grouped[(tier, cid)] = tuple(sorted(ids))
    return _StaffDirectory(grouped)


# --- shaping the monitor's inputs ---------------------------------------------


def _assess_deployments(
    program: Program,
    deployments: Sequence[Deployment],
    marks: dict[UUID, list[TrainerAttendance]],
    start: dt.date,
    end: dt.date,
    observed_at: dt.datetime,
) -> list[tuple[Deployment, RiskAssessment, AttendanceSignal]]:
    """One assessment per deployment active in the window.

    The window is CLIPPED to the deployment's own dates. A trainer who started on
    the 20th has not failed to mark the 1st to the 19th, and a monitor that says
    otherwise fires on every new deployment in its first month — which is how an
    alert feed becomes something people close without reading.
    """
    out: list[tuple[Deployment, RiskAssessment, AttendanceSignal]] = []
    for deployment in deployments:
        window_start = max(start, deployment.start_date or start)
        window_end = min(end, deployment.end_date or end)
        if window_end < window_start:
            continue

        rows = [
            r for r in marks.get(deployment.id, ()) if window_start <= r.mark_date <= window_end
        ]
        signal = AttendanceSignal(
            period_start=window_start,
            period_end=window_end,
            # `expand_period` materialises UNMARKED for every day no row exists
            # for. A sparse list would make the one failure mode this whole
            # detector family exists to catch invisible (§5).
            days=tuple(
                expand_period(window_start, window_end, {r.mark_date: r.mark for r in rows})
            ),
            elapsed_through=min(window_end, observed_at.date()),
            last_marked_at=max((r.marked_at for r in rows), default=None),
        )
        assessment = assess_risk(
            MonitorContext(
                program_id=program.id,
                college_id=program.college_id,
                program_type=program.type,
                as_of=observed_at,
                attendance=signal,
                # usage / syllabus stay None — see the module docstring. The
                # detectors are silent on a missing signal by design; passing a
                # zero would be asserting a fact nobody measured (R1).
            )
        )
        out.append((deployment, assessment, signal))
    return out


def _deployment_out(
    deployment: Deployment,
    assessment: RiskAssessment,
    signal: AttendanceSignal,
    audience: Persona,
    *,
    trainer_name: str,
    batch_name: str,
) -> DeploymentRiskOut:
    """Render one assessment through `build_alert()` for this caller's persona.

    `build_alert` raises on an external audience. It cannot here — the handler
    ran `require_internal()` first — and the call is left un-guarded on purpose:
    if that ordering is ever broken, a 500 naming §8 is the correct outcome, not
    a quietly delivered alert.

    The window comes off the signal the monitor actually looked at, not off the
    request. They differ whenever a deployment starts or ends mid-period, and
    reporting the requested window against a clipped assessment is how "3 of 31
    days marked" gets read as a crisis.
    """
    alert = build_alert(assessment, (audience,))
    return DeploymentRiskOut(
        deployment_id=deployment.id,
        trainer_name=trainer_name,
        batch_name=batch_name,
        period_start=signal.period_start,
        period_end=signal.period_end,
        elapsed_through=signal.elapsed_through,
        score=assessment.score,
        band=assessment.band,
        headline=alert.headline,
        lines=alert.lines,
        anomalies=tuple(AnomalyOut.of(a) for a in assessment.anomalies),
    )


# --- shaping the escalation engine's inputs -----------------------------------

#: The `SlaMetric` members this endpoint measures. The rest are omitted from
#: `SlaFacts.metrics` entirely, because `engine.evaluate_sla()` treats a missing
#: key as "not measured" and a present zero as a measurement — and an `LT` rule
#: against a defaulted zero fires on every subject nobody collected data for.
MEASURED_METRICS: Final[frozenset[SlaMetric]] = frozenset(
    {
        SlaMetric.TASK_HOURS_OVERDUE,
        SlaMetric.DOCUMENT_HOURS_UNSIGNED,
        SlaMetric.ATTENDANCE_UNMARKED_DAYS,
        SlaMetric.ATTENDANCE_HOURS_SINCE_MARK,
        SlaMetric.DELIVERY_RISK_SCORE,
    }
)


def _sla_metrics(
    assessed: Sequence[tuple[Deployment, RiskAssessment, AttendanceSignal]],
    tasks: Sequence[Task],
    documents: Sequence[ProgramDocument],
    observed_at: dt.datetime,
) -> dict[SlaMetric, Decimal]:
    """Measure, from the systems of record, what the rule table may refer to.

    Every value is a WORST CASE across the program: the most overdue task, the
    longest-unsigned document, the deployment with the most unmarked days, the
    stalest marking, the riskiest deployment. Averaging would let one healthy
    tracksheet hide a stopped one, and the SLA exists to notice the stopped one.

    A metric nobody could measure is left OUT of the mapping rather than set to
    zero. That is `engine.py`'s stated rule and it is load-bearing: an unmarked-
    day count of zero and an unmarked-day count nobody took are different facts.
    """
    metrics: dict[SlaMetric, Decimal] = {}

    overdue = [
        h
        for t in tasks
        if t.status is not TaskStatus.DONE and t.due_date is not None
        if (h := _hours_past(_end_of_day(t.due_date), observed_at)) is not None
    ]
    if overdue:
        metrics[SlaMetric.TASK_HOURS_OVERDUE] = max(overdue)

    unsigned = [
        h
        for d in documents
        if d.status != DocStatus.SIGNED and d.due_date is not None
        if (h := _hours_past(_end_of_day(d.due_date), observed_at)) is not None
    ]
    if unsigned:
        metrics[SlaMetric.DOCUMENT_HOURS_UNSIGNED] = max(unsigned)

    if assessed:
        unmarked = max(
            len([d for d in signal.elapsed_days() if d.mark is AttendanceMark.UNMARKED])
            for _, _, signal in assessed
        )
        metrics[SlaMetric.ATTENDANCE_UNMARKED_DAYS] = Decimal(unmarked)
        metrics[SlaMetric.DELIVERY_RISK_SCORE] = max(a.score for _, a, _ in assessed)

        # Hours SINCE a mark is unmeasurable when there has never been one. The
        # monitor already raises `attendance_marking_stale` for that case, so the
        # signal is not lost — it is just not expressible as an elapsed duration.
        stale = [
            h
            for _, _, signal in assessed
            if signal.last_marked_at is not None
            if (h := _hours_past(signal.last_marked_at, observed_at)) is not None
        ]
        if stale:
            metrics[SlaMetric.ATTENDANCE_HOURS_SINCE_MARK] = max(stale)

    return metrics


def _unmeasured(metrics: dict[SlaMetric, Decimal]) -> tuple[str, ...]:
    """Rule-table metrics this program carries no measurement for, in enum order."""
    return tuple(m.value for m in SlaMetric if m not in metrics)


# --- small conversions --------------------------------------------------------


def _as_of(as_of: dt.datetime | None) -> dt.datetime:
    """The observation instant, UTC (§11).

    The clock is read HERE and nowhere deeper: neither service calls
    `datetime.now()`, which is what makes a run reproducible from its inputs and
    lets a caller replay last Tuesday by passing `as_of`.
    """
    if as_of is None:
        return dt.datetime.now(dt.UTC)
    return as_of if as_of.tzinfo is not None else as_of.replace(tzinfo=dt.UTC)


def _period(
    period_start: dt.date | None, period_end: dt.date | None, observed_at: dt.datetime
) -> tuple[dt.date, dt.date]:
    """Resolve the observation window, defaulting to the calendar month of `as_of`.

    The month is the default because it is the period a payout cycle is cut on
    (§6), and the attendance gaps this feed exists to surface are the ones that
    block that cycle at month end.
    """
    today = observed_at.date()
    if period_start is None and period_end is None:
        last = calendar.monthrange(today.year, today.month)[1]
        return today.replace(day=1), today.replace(day=last)
    if period_start is None or period_end is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail="Give both period_start and period_end, or neither for the current month",
        )
    if period_end < period_start:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=f"period_end {period_end} precedes period_start {period_start}",
        )
    if (period_end - period_start).days + 1 > MAX_PERIOD_DAYS:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=(
                f"An observation window may span at most {MAX_PERIOD_DAYS} days; every day "
                "of it is materialised per deployment so that unmarked days are visible."
            ),
        )
    return period_start, period_end


def _end_of_day(on: dt.date) -> dt.datetime:
    """Midnight UTC ending `on` — the instant something due that day became late.

    Due dates are dates, and treating one as midnight at its START would report a
    task due today as a day overdue before the day has happened.
    """
    return dt.datetime.combine(on + dt.timedelta(days=1), dt.time.min, tzinfo=dt.UTC)


def _hours_past(deadline: dt.datetime, observed_at: dt.datetime) -> Decimal | None:
    """Hours from `deadline` to `observed_at`, or `None` if it has not passed."""
    seconds = (observed_at - deadline).total_seconds()
    if seconds <= 0:
        return None
    return (Decimal(seconds) / _SECONDS_PER_HOUR).quantize(_HOURS)
