import { createClient } from '@supabase/supabase-js'

/**
 * The one Supabase client for the app.
 *
 * The frontend talks to Supabase DIRECTLY with the user's JWT for standard
 * CRUD, and RLS decides what comes back. There is no permission logic in this
 * codebase that the database does not already enforce — UI that hides a button
 * is a convenience, never a control (CLAUDE.md R5). If a query returns rows the
 * user was entitled to them; if it returns none, the wall did its job.
 *
 * ANON KEY ONLY. The service-role key carries BYPASSRLS and must never appear
 * in anything that ships to a browser.
 */

const url = import.meta.env.VITE_SUPABASE_URL
const anonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

if (!url || !anonKey) {
  throw new Error(
    'Missing VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY.\n' +
      'Copy frontend/.env.example to frontend/.env.local and fill it in.',
  )
}

export const supabase = createClient(url, anonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
})

/**
 * Turn a PostgREST `{ data, error }` result into a value or a throw.
 *
 * TanStack Query decides success from whether the queryFn threw, and PostgREST
 * resolves its promise on failure. Without this every queryFn would have to
 * remember to rethrow, and the one that forgot would cache `null` as a
 * successful empty result — which for this app means an RLS refusal rendering
 * as "no rows" instead of as an error.
 */
export async function unwrap<T>(
  builder: PromiseLike<{ data: T | null; error: unknown }>,
): Promise<T> {
  const { data, error } = await builder
  if (error) throw error
  return (data ?? ([] as unknown)) as T
}

/** Narrow a PostgREST error into something worth showing a human. */
export function errorMessage(error: unknown): string {
  if (!error) return 'Unknown error'
  const e = error as { message?: string; details?: string; hint?: string; code?: string }

  // 42501 / RLS rejections are the interesting case: they mean the database
  // refused, which is usually a role/assignment problem rather than a bug.
  if (e.code === '42501' || e.message?.includes('row-level security')) {
    return 'Your role does not permit that action. If you expect to see this college, ask an admin to check your assignments.'
  }

  // 23505 unique violation and 23514 check violation are the two a data-entry
  // user hits routinely, and Postgres reports both by CONSTRAINT NAME. Left
  // untranslated they read as "duplicate key value violates unique constraint
  // \"deployments_trainer_batch_key\"" — which tells an Ops executive nothing
  // about what they did or how to fix it, and looks like the system broke.
  //
  // Matching on the constraint name rather than the message text is deliberate:
  // the name is declared in the migration and changes only when someone edits
  // that migration, whereas Postgres' prose varies by version.
  if (e.code === '23505') {
    const detail = `${e.message ?? ''} ${e.details ?? ''}`
    if (detail.includes('deployments_trainer_batch')) {
      return 'This trainer is already deployed to that batch from that start date. Edit the existing deployment instead of adding a second one.'
    }
    if (detail.includes('invoice')) {
      return 'That invoice number has already been issued. Invoice numbers are generated by the system and cannot repeat.'
    }
    if (detail.includes('trainers_pan')) {
      return 'A trainer with that PAN already exists. PAN is the identity key — search the roster rather than creating a duplicate.'
    }
    return 'That record already exists. Open the existing one and edit it rather than adding a duplicate.'
  }

  if (e.code === '23514') {
    const detail = `${e.message ?? ''} ${e.details ?? ''}`
    if (detail.includes('ifsc_length')) return 'IFSC must be exactly 11 characters, e.g. SBIN0001234.'
    if (detail.includes('ifsc_upper')) return 'IFSC must be uppercase.'
    if (detail.includes('account_digits')) return 'Bank account number must contain digits only — no spaces or dashes.'
    if (detail.includes('passout_year')) return 'Passout year looks wrong. Enter the full four-digit graduating year, e.g. 2027.'
    if (detail.includes('date_order')) return 'The end date cannot be before the start date.'
    return 'That value failed a validation rule in the database. Check the highlighted fields.'
  }

  return e.message || e.details || 'Something went wrong'
}
